### ISSUE TITLE
Add rarity filter to tower stash

### ISSUE THREAD

**Issue by Kvel2D** [Praytic/youtd2#251] opened 2023-10-18 05:58 UTC
Should work the same way as for item stash.

**Comment by Praytic** [comment] 2023-10-18 15:44
Currently it's not possible due to BottomMenuBar layout.

**Comment by Praytic** [comment] 2023-10-23 03:53
> @jdbuenol You could put the same 4 icons above the elements? Making it non-scroll/persist the location last looked could also be confusing as it could feel "stuck" in place. When I close out of a menu, I expect things to be "reset", which is normally fine when you have a large menu. When it is a scroll-only menu, then it feels bad to have to scroll a lot, and it would feel bad to have to scroll a lot left AND right if it is "frozen" to a previous session of looking at the towers (eg, I've maxed out Nature and it has been 15 rounds, now I want to check for a Lesser Wolves Den but the last time I checked I was looking at the Unique Nature towers, so now I have to scroll left to find a Lesser Wolves Den). 
> > @Praytic Tower stash doesn't need rarirty filters so much as items stash because of the following reasons:
In build mode you'll usually browse all the towers casually when you have free time. In upgrade mode you've an announcer which shows you which towers dropped with each wave, so you need to scroll only when decide to build a tower or you forgot which towers do you have (usually if you wait for a specific tower you'll see it in the feed). 
The problem is when the player is new and doesn't know all the towers, but the rarity filter won't help him. They still need to scroll all the towers to find the name which appeared in the feed. 
What I see that can resolve this issue and don't make UI polluted with buttons is to sort tower stash (and item stash) by rarity desc. The chance that the player wants to look at the last dropped tower with the most rarity is the highest. This was actually already implemented before and was lost after BottomMenuBar redesign.

**Comment by Praytic** [comment] 2023-12-19 21:57
Closing this issue because the current version of the UI has improved tower browsing capabilities, so it doesn't require more filters.

**Closed by Praytic** 2023-12-19 21:57 UTC
Labels: enhancement
