### ISSUE TITLE
Item "Pocket Emporium" can accumulate more than 5 charges

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#355] opened 2024-01-20 03:31 UTC
![image](https://github.com/Praytic/youtd2/assets/10060411/d10d63d8-d2f7-4f84-8d33-42a9768d7cd4)
![image](https://github.com/Praytic/youtd2/assets/10060411/118cd5c4-42e7-4aac-bc0e-cae61dabac43)
Reported by a player

**Comment by Kvel2D** [comment] 2024-01-20 07:10
In both screenshots I can see that "Pocket Emporium" doesn't go above 5 charges. Wrong report?

**Comment by Kvel2D** [comment] 2024-01-23 18:07
Closing because I couldn't reproduce the bug and the screenshots don't demonstrate the bug.

**Closed by Kvel2D** 2024-01-23 18:07 UTC
Labels: bug
