### ISSUE TITLE
can only choose one element type for towers

### ISSUE THREAD

**Issue by foxyinaboxy314159** [Praytic/youtd2#69] opened 2023-05-01 13:53 UTC

**Comment by Kvel2D** [comment] 2023-05-02 12:00
Once you have selected an element you can press the "Escape" key to close the tower list. After that you will be able to select another element.

Does that solve the problem?

**Comment by Kvel2D** [comment] 2023-07-15 09:29
Closing this since the issue is old and not relevant to new UI.

**Closed by Kvel2D** 2023-07-15 09:29 UTC
