### ISSUE TITLE
Brainstorm new titles and descriptions for items and oils based on the icon

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#111] opened 2023-07-11 00:10 UTC

**Comment by Kvel2D** [comment] 2023-11-05 10:34
Started working on this in this google sheet:
https://docs.google.com/spreadsheets/d/1GzsSddZCpvstKTwQKm7hLkG3Sp_-FaKfIeu030uXVos/edit?usp=sharing

**Comment by Kvel2D** [comment] 2023-11-07 15:02
Duplicate of #189

**Closed by Kvel2D** 2023-11-07 15:02 UTC
